# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [pre-commit]
    language: system
    entry: isort
    types: [python]

  - id: black
    name: black
    stages: [pre-commit]
    language: system
    entry: black
    types: [python]

  - id: flake8
    name: flake8
    stages: [pre-commit]
    language: system
    entry: flake8
    types: [python]

  - id: mypy
    name: mypy
    stages: [pre-commit]
    language: system
    entry: mypy
    types: [python]
    require_serial: true

  - id: pytest-cov
    name: pytest
    stages: [pre-commit]
    language: system
    entry: pytest --cov --cov-fail-under=90
    types: [python]
    pass_filenames: false
