name: Docker build test

on: 
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -f ./docker/Dockerfile -t within:test .

      - name: Smoke test docker image
        run: |
          docker run -d --rm within:test
          sleep 5
          docker stop within:test
